@baseUrl = http://localhost:8089

### Create Metric
# @prompt name
# @prompt inputFrequency
POST {{baseUrl}}/metrics
Content-Type: application/json

{
    "name": "{{name}}",
    "input_frequency": "{{inputFrequency}}"
}

### Get Metric by ID
# @prompt metricId
GET {{baseUrl}}/metrics/{{metricId}}

### Get All Metrics
GET {{baseUrl}}/metrics

### Get All Metrics with Readings
GET {{baseUrl}}/metrics?with_readings=true
